[tools]
aube = "latest"
pnpm = "latest"
hk = "latest"
jd = "latest"
jq = "latest"
node = "24"
pkl = "latest"

[env]
_.file = ".env"
HK_MISE = "1"

[hooks]
postinstall = ["hk install --mise", "aube install"]
