name: Lint & Formatting

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v4

      - run: aube install --frozen-lockfile

      - run: aube run typecheck
        if: always()

      - run: aube run lint
        if: always()

      - run: aube run format:check
        if: always()
